-- UTBMS litigation task codes (leaf level) and activity codes. Mirrors src/lib/utbms.ts.
insert into utbms_codes (code, kind, phase, label) values
  ('L110', 'task', 'L100', 'Fact Investigation/Development'),
  ('L120', 'task', 'L100', 'Analysis/Strategy'),
  ('L130', 'task', 'L100', 'Experts/Consultants'),
  ('L140', 'task', 'L100', 'Document/File Management'),
  ('L150', 'task', 'L100', 'Budgeting'),
  ('L160', 'task', 'L100', 'Settlement/Non-Binding ADR'),
  ('L190', 'task', 'L100', 'Other Case Assessment, Development and Administration'),
  ('L210', 'task', 'L200', 'Pleadings'),
  ('L220', 'task', 'L200', 'Preliminary Injunctions/Provisional Remedies'),
  ('L230', 'task', 'L200', 'Court Mandated Conferences'),
  ('L240', 'task', 'L200', 'Dispositive Motions'),
  ('L250', 'task', 'L200', 'Other Written Motions and Submissions'),
  ('L260', 'task', 'L200', 'Class Action Certification and Notice'),
  ('L310', 'task', 'L300', 'Written Discovery'),
  ('L320', 'task', 'L300', 'Document Production'),
  ('L330', 'task', 'L300', 'Depositions'),
  ('L340', 'task', 'L300', 'Expert Discovery'),
  ('L350', 'task', 'L300', 'Discovery Motions'),
  ('L390', 'task', 'L300', 'Other Discovery'),
  ('L410', 'task', 'L400', 'Fact Witnesses'),
  ('L420', 'task', 'L400', 'Expert Witnesses'),
  ('L430', 'task', 'L400', 'Written Motions and Submissions'),
  ('L440', 'task', 'L400', 'Other Trial Preparation and Support'),
  ('L450', 'task', 'L400', 'Trial and Hearing Attendance'),
  ('L460', 'task', 'L400', 'Post-Trial Motions and Submissions'),
  ('L470', 'task', 'L400', 'Enforcement'),
  ('L510', 'task', 'L500', 'Appellate Motions and Submissions'),
  ('L520', 'task', 'L500', 'Appellate Briefs'),
  ('L530', 'task', 'L500', 'Oral Argument'),
  ('A101', 'activity', null, 'Plan and prepare for'),
  ('A102', 'activity', null, 'Research'),
  ('A103', 'activity', null, 'Draft/revise'),
  ('A104', 'activity', null, 'Review/analyze'),
  ('A105', 'activity', null, 'Communicate (in firm)'),
  ('A106', 'activity', null, 'Communicate (with client)'),
  ('A107', 'activity', null, 'Communicate (other outside counsel)'),
  ('A108', 'activity', null, 'Communicate (other external)'),
  ('A109', 'activity', null, 'Appear for/attend'),
  ('A110', 'activity', null, 'Manage data/files'),
  ('A111', 'activity', null, 'Other')
on conflict (code) do nothing;
